/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2026-04-06 13:45:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.rodado;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.sample.core.domain.Rodado;

public final class rodadoPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


    // Helper para obtener valor de getter via reflection (evita casteos en el JSP)
    private String safeGet(Class<?> cls, Object obj, String methodName) {
        try {
            return String.valueOf(cls.getMethod(methodName).invoke(obj));
        } catch (Exception e) {
            return "";
        }
    }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/6to%20TC/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153395882000L));
    _jspx_dependants.put("file:/C:/Users/6to%20TC/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1775476805932L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.sample.core.domain.Rodado");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Gestión de Rodados</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap 5 -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Bootstrap Icons -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Google Fonts -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Syne:wght@700;800&family=DM+Sans:wght@300;400;500;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- SweetAlert2 -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --primary:       #1a1f36;\r\n");
      out.write("            --accent:        #3b6ef8;\r\n");
      out.write("            --accent-light:  #e8eeff;\r\n");
      out.write("            --danger:        #e84545;\r\n");
      out.write("            --success:       #27b08b;\r\n");
      out.write("            --surface:       #f4f6fb;\r\n");
      out.write("            --card-bg:       #ffffff;\r\n");
      out.write("            --text-main:     #1a1f36;\r\n");
      out.write("            --text-muted:    #7b8299;\r\n");
      out.write("            --border:        #e4e8f4;\r\n");
      out.write("            --shadow-sm:     0 2px 8px rgba(59,110,248,.08);\r\n");
      out.write("            --shadow-md:     0 8px 32px rgba(26,31,54,.13);\r\n");
      out.write("            --radius:        14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        *, *::before, *::after { box-sizing: border-box; }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'DM Sans', sans-serif;\r\n");
      out.write("            background: var(--surface);\r\n");
      out.write("            color: var(--text-main);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ── Sidebar strip ──────────────────────────────── */\r\n");
      out.write("        .sidebar-strip {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            left: 0; top: 0; bottom: 0;\r\n");
      out.write("            width: 5px;\r\n");
      out.write("            background: linear-gradient(180deg, var(--accent) 0%, #7c3aed 100%);\r\n");
      out.write("            z-index: 1000;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ── Topbar ─────────────────────────────────────── */\r\n");
      out.write("        .topbar {\r\n");
      out.write("            background: var(--card-bg);\r\n");
      out.write("            border-bottom: 1px solid var(--border);\r\n");
      out.write("            padding: 0 2rem;\r\n");
      out.write("            height: 64px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            position: sticky;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            z-index: 900;\r\n");
      out.write("            box-shadow: var(--shadow-sm);\r\n");
      out.write("        }\r\n");
      out.write("        .topbar-brand {\r\n");
      out.write("            font-family: 'Syne', sans-serif;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            font-size: 1.25rem;\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("            letter-spacing: -.5px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: .6rem;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("        .topbar-brand .brand-dot {\r\n");
      out.write("            width: 10px; height: 10px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            background: var(--accent);\r\n");
      out.write("        }\r\n");
      out.write("        .topbar-right {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        .topbar-user {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: .5rem;\r\n");
      out.write("            font-size: .875rem;\r\n");
      out.write("            color: var(--text-muted);\r\n");
      out.write("        }\r\n");
      out.write("        .user-avatar {\r\n");
      out.write("            width: 36px; height: 36px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            background: linear-gradient(135deg, var(--accent), #7c3aed);\r\n");
      out.write("            display: flex; align-items: center; justify-content: center;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            font-size: .8rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ── Main wrapper ───────────────────────────────── */\r\n");
      out.write("        .main-wrapper {\r\n");
      out.write("            padding: 2rem 2rem 2rem 2.5rem;\r\n");
      out.write("            max-width: 1400px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ── Page header ────────────────────────────────── */\r\n");
      out.write("        .page-header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: flex-end;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            margin-bottom: 1.75rem;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            gap: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        .page-header-left h1 {\r\n");
      out.write("            font-family: 'Syne', sans-serif;\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            line-height: 1;\r\n");
      out.write("        }\r\n");
      out.write("        .page-header-left .breadcrumb-text {\r\n");
      out.write("            font-size: .8rem;\r\n");
      out.write("            color: var(--text-muted);\r\n");
      out.write("            margin-top: .35rem;\r\n");
      out.write("        }\r\n");
      out.write("        .breadcrumb-text i { margin-right: .25rem; }\r\n");
      out.write("\r\n");
      out.write("        /* ── Stats row ──────────────────────────────────── */\r\n");
      out.write("        .stat-card {\r\n");
      out.write("            background: var(--card-bg);\r\n");
      out.write("            border-radius: var(--radius);\r\n");
      out.write("            border: 1px solid var(--border);\r\n");
      out.write("            padding: 1.25rem 1.5rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 1rem;\r\n");
      out.write("            box-shadow: var(--shadow-sm);\r\n");
      out.write("            transition: transform .2s, box-shadow .2s;\r\n");
      out.write("        }\r\n");
      out.write("        .stat-card:hover { transform: translateY(-2px); box-shadow: var(--shadow-md); }\r\n");
      out.write("        .stat-icon {\r\n");
      out.write("            width: 48px; height: 48px;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            display: flex; align-items: center; justify-content: center;\r\n");
      out.write("            font-size: 1.4rem;\r\n");
      out.write("            flex-shrink: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .stat-icon.blue  { background: var(--accent-light); color: var(--accent); }\r\n");
      out.write("        .stat-icon.green { background: #e6faf4; color: var(--success); }\r\n");
      out.write("        .stat-icon.red   { background: #ffeaea; color: var(--danger); }\r\n");
      out.write("        .stat-icon.purple{ background: #f0ebff; color: #7c3aed; }\r\n");
      out.write("        .stat-value { font-family: 'Syne', sans-serif; font-size: 1.6rem; font-weight: 800; line-height: 1; }\r\n");
      out.write("        .stat-label { font-size: .78rem; color: var(--text-muted); margin-top: .2rem; }\r\n");
      out.write("\r\n");
      out.write("        /* ── Table card ─────────────────────────────────── */\r\n");
      out.write("        .table-card {\r\n");
      out.write("            background: var(--card-bg);\r\n");
      out.write("            border-radius: var(--radius);\r\n");
      out.write("            border: 1px solid var(--border);\r\n");
      out.write("            box-shadow: var(--shadow-md);\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        .table-card-header {\r\n");
      out.write("            padding: 1.25rem 1.5rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            border-bottom: 1px solid var(--border);\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            gap: .75rem;\r\n");
      out.write("        }\r\n");
      out.write("        .table-card-title {\r\n");
      out.write("            font-family: 'Syne', sans-serif;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            font-size: 1.05rem;\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: .5rem;\r\n");
      out.write("        }\r\n");
      out.write("        .table-card-title i { color: var(--accent); }\r\n");
      out.write("\r\n");
      out.write("        /* ── Search input ───────────────────────────────── */\r\n");
      out.write("        .search-input-wrap { position: relative; }\r\n");
      out.write("        .search-input-wrap i {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: .875rem; top: 50%;\r\n");
      out.write("            transform: translateY(-50%);\r\n");
      out.write("            color: var(--text-muted);\r\n");
      out.write("            font-size: .9rem;\r\n");
      out.write("        }\r\n");
      out.write("        .search-input {\r\n");
      out.write("            border: 1px solid var(--border);\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            padding: .45rem .875rem .45rem 2.2rem;\r\n");
      out.write("            font-size: .85rem;\r\n");
      out.write("            font-family: 'DM Sans', sans-serif;\r\n");
      out.write("            width: 220px;\r\n");
      out.write("            background: var(--surface);\r\n");
      out.write("            color: var(--text-main);\r\n");
      out.write("            transition: border-color .2s, box-shadow .2s;\r\n");
      out.write("        }\r\n");
      out.write("        .search-input:focus {\r\n");
      out.write("            outline: none;\r\n");
      out.write("            border-color: var(--accent);\r\n");
      out.write("            box-shadow: 0 0 0 3px rgba(59,110,248,.12);\r\n");
      out.write("            background: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ── Table ──────────────────────────────────────── */\r\n");
      out.write("        .rodados-table { margin: 0; font-size: .875rem; }\r\n");
      out.write("        .rodados-table thead tr {\r\n");
      out.write("            background: var(--surface);\r\n");
      out.write("        }\r\n");
      out.write("        .rodados-table thead th {\r\n");
      out.write("            color: var(--text-muted);\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: .75rem;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            letter-spacing: .07em;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: .875rem 1rem;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("        }\r\n");
      out.write("        .rodados-table tbody tr {\r\n");
      out.write("            border-bottom: 1px solid var(--border);\r\n");
      out.write("            transition: background .15s;\r\n");
      out.write("        }\r\n");
      out.write("        .rodados-table tbody tr:hover { background: var(--accent-light); }\r\n");
      out.write("        .rodados-table tbody td {\r\n");
      out.write("            padding: .875rem 1rem;\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: var(--text-main);\r\n");
      out.write("        }\r\n");
      out.write("        .rodados-table tbody tr:last-child { border-bottom: none; }\r\n");
      out.write("\r\n");
      out.write("        /* ID badge */\r\n");
      out.write("        .id-badge {\r\n");
      out.write("            background: var(--accent-light);\r\n");
      out.write("            color: var(--accent);\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            font-size: .78rem;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            padding: .2rem .55rem;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Patente badge */\r\n");
      out.write("        .patente-badge {\r\n");
      out.write("            font-family: 'Syne', sans-serif;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            font-size: .82rem;\r\n");
      out.write("            background: var(--primary);\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            padding: .25rem .65rem;\r\n");
      out.write("            letter-spacing: .08em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Color dot */\r\n");
      out.write("        .color-dot {\r\n");
      out.write("            width: 14px; height: 14px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            border: 2px solid rgba(0,0,0,.1);\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("            margin-right: .4rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ── Action buttons ─────────────────────────────── */\r\n");
      out.write("        .btn-action {\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            padding: .35rem .7rem;\r\n");
      out.write("            font-size: .8rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: .3rem;\r\n");
      out.write("            transition: opacity .15s, transform .15s;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-action:hover { opacity: .85; transform: translateY(-1px); }\r\n");
      out.write("        .btn-edit  { background: var(--accent-light); color: var(--accent); }\r\n");
      out.write("        .btn-delete{ background: #ffeaea; color: var(--danger); }\r\n");
      out.write("\r\n");
      out.write("        /* ── Primary button ─────────────────────────────── */\r\n");
      out.write("        .btn-primary-custom {\r\n");
      out.write("            background: linear-gradient(135deg, var(--accent), #5a8aff);\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            padding: .6rem 1.4rem;\r\n");
      out.write("            font-family: 'DM Sans', sans-serif;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: .9rem;\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: .5rem;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            box-shadow: 0 4px 14px rgba(59,110,248,.35);\r\n");
      out.write("            transition: box-shadow .2s, transform .2s;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-primary-custom:hover {\r\n");
      out.write("            box-shadow: 0 6px 20px rgba(59,110,248,.5);\r\n");
      out.write("            transform: translateY(-1px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ── Empty state ────────────────────────────────── */\r\n");
      out.write("        .empty-state {\r\n");
      out.write("            padding: 3.5rem 1rem;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .empty-state i { font-size: 3rem; color: var(--border); }\r\n");
      out.write("        .empty-state p { color: var(--text-muted); margin-top: .75rem; font-size: .9rem; }\r\n");
      out.write("\r\n");
      out.write("        /* ── Modal ──────────────────────────────────────── */\r\n");
      out.write("        .modal-content {\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: var(--radius);\r\n");
      out.write("            box-shadow: var(--shadow-md);\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        .modal-header {\r\n");
      out.write("            background: linear-gradient(135deg, var(--primary), #2d3566);\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 1.25rem 1.75rem;\r\n");
      out.write("        }\r\n");
      out.write("        .modal-header .modal-title {\r\n");
      out.write("            font-family: 'Syne', sans-serif;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: .6rem;\r\n");
      out.write("        }\r\n");
      out.write("        .modal-header .btn-close {\r\n");
      out.write("            filter: invert(1) brightness(2);\r\n");
      out.write("            opacity: .7;\r\n");
      out.write("        }\r\n");
      out.write("        .modal-header .btn-close:hover { opacity: 1; }\r\n");
      out.write("        .modal-body { padding: 1.75rem; background: var(--surface); }\r\n");
      out.write("\r\n");
      out.write("        /* ── Scrollbar ──────────────────────────────────── */\r\n");
      out.write("        ::-webkit-scrollbar { width: 6px; height: 6px; }\r\n");
      out.write("        ::-webkit-scrollbar-track { background: transparent; }\r\n");
      out.write("        ::-webkit-scrollbar-thumb { background: var(--border); border-radius: 99px; }\r\n");
      out.write("\r\n");
      out.write("        /* ── Responsive ─────────────────────────────────── */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .main-wrapper { padding: 1rem 1rem 1rem 1.25rem; }\r\n");
      out.write("            .page-header h1 { font-size: 1.5rem; }\r\n");
      out.write("            .search-input { width: 160px; }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ── Fade-in animation ──────────────────────────── */\r\n");
      out.write("        @keyframes fadeUp {\r\n");
      out.write("            from { opacity: 0; transform: translateY(16px); }\r\n");
      out.write("            to   { opacity: 1; transform: translateY(0); }\r\n");
      out.write("        }\r\n");
      out.write("        .fade-up { animation: fadeUp .4s ease both; }\r\n");
      out.write("        .fade-up:nth-child(2) { animation-delay: .07s; }\r\n");
      out.write("        .fade-up:nth-child(3) { animation-delay: .14s; }\r\n");
      out.write("        .fade-up:nth-child(4) { animation-delay: .21s; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Sidebar accent strip -->\r\n");
      out.write("<div class=\"sidebar-strip\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- ── Topbar ───────────────────────────────────────────── -->\r\n");
      out.write("<nav class=\"topbar\">\r\n");
      out.write("    <a href=\"#\" class=\"topbar-brand\">\r\n");
      out.write("        <div class=\"brand-dot\"></div>\r\n");
      out.write("        FleetCore\r\n");
      out.write("    </a>\r\n");
      out.write("    <div class=\"topbar-right\">\r\n");
      out.write("        <div class=\"topbar-user\">\r\n");
      out.write("            <div class=\"user-avatar\">AD</div>\r\n");
      out.write("            <span class=\"d-none d-sm-inline\">Admin</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- ── Main ─────────────────────────────────────────────── -->\r\n");
      out.write("<div class=\"main-wrapper\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Page header -->\r\n");
      out.write("    <div class=\"page-header fade-up\">\r\n");
      out.write("        <div class=\"page-header-left\">\r\n");
      out.write("            <div class=\"breadcrumb-text\">\r\n");
      out.write("                <i class=\"bi bi-house-fill\"></i> Inicio &rsaquo; Rodados\r\n");
      out.write("            </div>\r\n");
      out.write("            <h1>Gestión de Rodados</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button class=\"btn-primary-custom\" data-bs-toggle=\"modal\" data-bs-target=\"#modalRodado\">\r\n");
      out.write("            <i class=\"bi bi-plus-lg\"></i> Nuevo Rodado\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Stats -->\r\n");
      out.write("    <div class=\"row g-3 mb-4\">\r\n");
      out.write("        <div class=\"col-6 col-md-3 fade-up\">\r\n");
      out.write("            <div class=\"stat-card\">\r\n");
      out.write("                <div class=\"stat-icon blue\"><i class=\"bi bi-truck\"></i></div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"stat-value\" id=\"stat-total\">—</div>\r\n");
      out.write("                    <div class=\"stat-label\">Total Rodados</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-6 col-md-3 fade-up\">\r\n");
      out.write("            <div class=\"stat-card\">\r\n");
      out.write("                <div class=\"stat-icon green\"><i class=\"bi bi-check-circle\"></i></div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"stat-value\" id=\"stat-active\">—</div>\r\n");
      out.write("                    <div class=\"stat-label\">Activos</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-6 col-md-3 fade-up\">\r\n");
      out.write("            <div class=\"stat-card\">\r\n");
      out.write("                <div class=\"stat-icon purple\"><i class=\"bi bi-fuel-pump\"></i></div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"stat-value\" id=\"stat-types\">—</div>\r\n");
      out.write("                    <div class=\"stat-label\">Tipos de Rodado</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-6 col-md-3 fade-up\">\r\n");
      out.write("            <div class=\"stat-card\">\r\n");
      out.write("                <div class=\"stat-icon red\"><i class=\"bi bi-exclamation-triangle\"></i></div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"stat-value\" id=\"stat-pending\">—</div>\r\n");
      out.write("                    <div class=\"stat-label\">Pendientes</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Table card -->\r\n");
      out.write("    <div class=\"table-card fade-up\">\r\n");
      out.write("        <div class=\"table-card-header\">\r\n");
      out.write("            <div class=\"table-card-title\">\r\n");
      out.write("                <i class=\"bi bi-table\"></i> Listado de Rodados\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"search-input-wrap\">\r\n");
      out.write("                <i class=\"bi bi-search\"></i>\r\n");
      out.write("                <input type=\"text\" class=\"search-input\" id=\"tableSearch\" placeholder=\"Buscar rodado...\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"table-responsive\">\r\n");
      out.write("            <table class=\"table rodados-table table-hover\" id=\"rodadosTable\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>ID</th>\r\n");
      out.write("                        <th>Tipo de Caja</th>\r\n");
      out.write("                        <th>Tipo</th>\r\n");
      out.write("                        <th>Consumo</th>\r\n");
      out.write("                        <th>Puertas</th>\r\n");
      out.write("                        <th>T. Rodado</th>\r\n");
      out.write("                        <th>Patente</th>\r\n");
      out.write("                        <th>Motor</th>\r\n");
      out.write("                        <th>Color</th>\r\n");
      out.write("                        <th>Baúl</th>\r\n");
      out.write("                        <th>Acciones</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    ");

                        java.util.List<?> rodados = (java.util.List<?>) request.getAttribute("rodado");
                        if (rodados == null || rodados.isEmpty()) {
                    
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"11\">\r\n");
      out.write("                            <div class=\"empty-state\">\r\n");
      out.write("                                <i class=\"bi bi-inbox\"></i>\r\n");
      out.write("                                <p>No hay rodados registrados aún.<br>¡Agregá el primero con el botón de arriba!</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");

                        } else {
                            for (Object item : rodados) {
                                // Acceso via reflection para compatibilidad con cualquier clase de modelo
                                Class<?> cls = item.getClass();
                                String id         = safeGet(cls, item, "getId");
                                String tipoCaja   = safeGet(cls, item, "getTipocaja");
                                String tipo       = safeGet(cls, item, "getTipo");
                                String consumo    = safeGet(cls, item, "getTipoconsumo");
                                String puertas    = safeGet(cls, item, "getPuertas");
                                String tipoRodado = safeGet(cls, item, "getTipoderodado");
                                String patente    = safeGet(cls, item, "getPatente");
                                String motor      = safeGet(cls, item, "getMotor");
                                String color      = safeGet(cls, item, "getColor");
                                String baul       = safeGet(cls, item, "getBaul");
                    
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td><span class=\"id-badge\">");
      out.print( id );
      out.write("</span></td>\r\n");
      out.write("                        <td>");
      out.print( tipoCaja );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( tipo );
      out.write("</td>\r\n");
      out.write("                        <td><i class=\"bi bi-fuel-pump text-muted me-1\"></i>");
      out.print( consumo );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( puertas );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( tipoRodado );
      out.write("</td>\r\n");
      out.write("                        <td><span class=\"patente-badge\">");
      out.print( patente );
      out.write("</span></td>\r\n");
      out.write("                        <td>");
      out.print( motor );
      out.write("</td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <span class=\"color-dot\" style=\"background:");
      out.print( color.toLowerCase() );
      out.write("\"></span>\r\n");
      out.write("                            ");
      out.print( color );
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td><i class=\"bi bi-briefcase text-muted me-1\"></i>");
      out.print( baul );
      out.write("</td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/RodadoServlet?accion=editar&id=");
      out.print( id );
      out.write("\"\r\n");
      out.write("                               class=\"btn-action btn-edit\" title=\"Editar\">\r\n");
      out.write("                                <i class=\"bi bi-pencil-fill\"></i> Editar\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <button class=\"btn-action btn-delete ms-1\"\r\n");
      out.write("                                    onclick=\"confirmarEliminar('");
      out.print( id );
      out.write("')\"\r\n");
      out.write("                                    title=\"Eliminar\">\r\n");
      out.write("                                <i class=\"bi bi-trash3-fill\"></i> Eliminar\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");

                            }
                        }
                    
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div><!-- /table-card -->\r\n");
      out.write("\r\n");
      out.write("</div><!-- /main-wrapper -->\r\n");
      out.write("\r\n");
      out.write("<!-- ────────────────────────────────────────────────────── -->\r\n");
      out.write("<!-- Modal: Nuevo Rodado                                   -->\r\n");
      out.write("<!-- ────────────────────────────────────────────────────── -->\r\n");
      out.write("<div class=\"modal fade\" id=\"modalRodado\" tabindex=\"-1\" aria-labelledby=\"modalRodadoLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\" id=\"modalRodadoLabel\">\r\n");
      out.write("                    <i class=\"bi bi-truck\"></i> Nuevo Rodado\r\n");
      out.write("                </h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Cerrar\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <!-- rodadoForm.jsp se incluye dentro del modal -->\r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "rodadoForm.jsp", out, false);
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- ── Scripts ───────────────────────────────────────────── -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/scripts/agregarRodado.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
