/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2026-04-06 14:18:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.rodado;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class rodadoForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

    boolean isStandalone = (request.getAttribute("_embedded") == null);

      out.write("\r\n");
      out.write("\r\n");
 if (isStandalone) { 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Formulario de Rodado</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Syne:wght@700;800&family=DM+Sans:wght@300;400;500;600&display=swap\" rel=\"stylesheet\">\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    :root {\r\n");
      out.write("        --primary:      #1a1f36;\r\n");
      out.write("        --accent:       #3b6ef8;\r\n");
      out.write("        --accent-light: #e8eeff;\r\n");
      out.write("        --success:      #27b08b;\r\n");
      out.write("        --surface:      #f4f6fb;\r\n");
      out.write("        --card-bg:      #ffffff;\r\n");
      out.write("        --text-main:    #1a1f36;\r\n");
      out.write("        --text-muted:   #7b8299;\r\n");
      out.write("        --border:       #e4e8f4;\r\n");
      out.write("        --radius:       14px;\r\n");
      out.write("        --shadow-md:    0 8px 32px rgba(26,31,54,.13);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ── Standalone wrapper ─────────────────────── */\r\n");
      out.write("    .form-standalone-wrap {\r\n");
      out.write("        font-family: 'DM Sans', sans-serif;\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("        background: var(--surface);\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        padding: 2rem 1rem;\r\n");
      out.write("    }\r\n");
      out.write("    .form-standalone-inner {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        max-width: 780px;\r\n");
      out.write("    }\r\n");
      out.write("    .form-standalone-header {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-bottom: 1.5rem;\r\n");
      out.write("    }\r\n");
      out.write("    .form-standalone-header h1 {\r\n");
      out.write("        font-family: 'Syne', sans-serif;\r\n");
      out.write("        font-size: 1.9rem;\r\n");
      out.write("        font-weight: 800;\r\n");
      out.write("        color: var(--primary);\r\n");
      out.write("        margin: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .form-standalone-header p {\r\n");
      out.write("        color: var(--text-muted);\r\n");
      out.write("        font-size: .875rem;\r\n");
      out.write("        margin-top: .3rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ── Card ───────────────────────────────────── */\r\n");
      out.write("    .rodado-form-card {\r\n");
      out.write("        background: var(--card-bg);\r\n");
      out.write("        border-radius: var(--radius);\r\n");
      out.write("        border: 1px solid var(--border);\r\n");
      out.write("        box-shadow: var(--shadow-md);\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("    .rodado-form-card .card-section-header {\r\n");
      out.write("        background: var(--surface);\r\n");
      out.write("        border-bottom: 1px solid var(--border);\r\n");
      out.write("        padding: .75rem 1.5rem;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: .5rem;\r\n");
      out.write("        font-size: .75rem;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("        letter-spacing: .1em;\r\n");
      out.write("        color: var(--text-muted);\r\n");
      out.write("    }\r\n");
      out.write("    .rodado-form-card .card-section-header i {\r\n");
      out.write("        color: var(--accent);\r\n");
      out.write("        font-size: .95rem;\r\n");
      out.write("    }\r\n");
      out.write("    .rodado-form-card .card-body-inner {\r\n");
      out.write("        padding: 1.5rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ── Form controls ──────────────────────────── */\r\n");
      out.write("    .form-label-custom {\r\n");
      out.write("        font-size: .8rem;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        color: var(--text-muted);\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("        letter-spacing: .06em;\r\n");
      out.write("        margin-bottom: .4rem;\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("    .form-control-custom,\r\n");
      out.write("    .form-select-custom {\r\n");
      out.write("        font-family: 'DM Sans', sans-serif;\r\n");
      out.write("        font-size: .9rem;\r\n");
      out.write("        color: var(--text-main);\r\n");
      out.write("        background: var(--surface);\r\n");
      out.write("        border: 1.5px solid var(--border);\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        padding: .6rem .95rem;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        transition: border-color .2s, box-shadow .2s, background .2s;\r\n");
      out.write("        appearance: none;\r\n");
      out.write("        -webkit-appearance: none;\r\n");
      out.write("    }\r\n");
      out.write("    .form-control-custom:focus,\r\n");
      out.write("    .form-select-custom:focus {\r\n");
      out.write("        outline: none;\r\n");
      out.write("        border-color: var(--accent);\r\n");
      out.write("        box-shadow: 0 0 0 3.5px rgba(59,110,248,.14);\r\n");
      out.write("        background: #fff;\r\n");
      out.write("    }\r\n");
      out.write("    .form-control-custom::placeholder { color: var(--border); }\r\n");
      out.write("\r\n");
      out.write("    /* Select arrow */\r\n");
      out.write("    .select-wrap {\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("    .select-wrap::after {\r\n");
      out.write("        content: '\\F282';\r\n");
      out.write("        font-family: 'Bootstrap-Icons';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        right: .9rem;\r\n");
      out.write("        top: 50%;\r\n");
      out.write("        transform: translateY(-50%);\r\n");
      out.write("        color: var(--text-muted);\r\n");
      out.write("        pointer-events: none;\r\n");
      out.write("        font-size: .9rem;\r\n");
      out.write("    }\r\n");
      out.write("    .select-wrap select { padding-right: 2.2rem; }\r\n");
      out.write("\r\n");
      out.write("    /* Input with icon prefix */\r\n");
      out.write("    .input-icon-wrap { position: relative; }\r\n");
      out.write("    .input-icon-wrap i {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        left: .9rem;\r\n");
      out.write("        top: 50%;\r\n");
      out.write("        transform: translateY(-50%);\r\n");
      out.write("        color: var(--text-muted);\r\n");
      out.write("        font-size: .95rem;\r\n");
      out.write("        pointer-events: none;\r\n");
      out.write("    }\r\n");
      out.write("    .input-icon-wrap input { padding-left: 2.4rem; }\r\n");
      out.write("\r\n");
      out.write("    /* Field group mb */\r\n");
      out.write("    .field-group { margin-bottom: 1.1rem; }\r\n");
      out.write("    .field-group:last-child { margin-bottom: 0; }\r\n");
      out.write("\r\n");
      out.write("    /* ── Submit button ──────────────────────────── */\r\n");
      out.write("    .btn-guardar {\r\n");
      out.write("        background: linear-gradient(135deg, #27b08b, #1d8c6e);\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        padding: .8rem 1.5rem;\r\n");
      out.write("        font-family: 'DM Sans', sans-serif;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        gap: .6rem;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        box-shadow: 0 4px 14px rgba(39,176,139,.35);\r\n");
      out.write("        transition: box-shadow .2s, transform .2s;\r\n");
      out.write("        margin-top: .5rem;\r\n");
      out.write("    }\r\n");
      out.write("    .btn-guardar:hover {\r\n");
      out.write("        box-shadow: 0 7px 22px rgba(39,176,139,.5);\r\n");
      out.write("        transform: translateY(-1px);\r\n");
      out.write("    }\r\n");
      out.write("    .btn-guardar:active { transform: translateY(0); }\r\n");
      out.write("\r\n");
      out.write("    /* ── Back link (standalone) ─────────────────── */\r\n");
      out.write("    .back-link {\r\n");
      out.write("        display: inline-flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: .4rem;\r\n");
      out.write("        color: var(--text-muted);\r\n");
      out.write("        font-size: .85rem;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        margin-bottom: 1.25rem;\r\n");
      out.write("        transition: color .15s;\r\n");
      out.write("    }\r\n");
      out.write("    .back-link:hover { color: var(--accent); }\r\n");
      out.write("\r\n");
      out.write("    /* ── Divider ────────────────────────────────── */\r\n");
      out.write("    .form-divider {\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-top: 1px solid var(--border);\r\n");
      out.write("        margin: .25rem 0 1.25rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ── Fade-up ────────────────────────────────── */\r\n");
      out.write("    @keyframes fadeUp {\r\n");
      out.write("        from { opacity: 0; transform: translateY(14px); }\r\n");
      out.write("        to   { opacity: 1; transform: translateY(0); }\r\n");
      out.write("    }\r\n");
      out.write("    .form-standalone-inner { animation: fadeUp .4s ease both; }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
 if (isStandalone) { 
      out.write("\r\n");
      out.write("<body style=\"margin:0;padding:0;\">\r\n");
      out.write("<div class=\"form-standalone-wrap\">\r\n");
      out.write("    <div class=\"form-standalone-inner\">\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/rodado/rodadoPage.jsp\" class=\"back-link\">\r\n");
      out.write("            <i class=\"bi bi-arrow-left\"></i> Volver al listado\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"form-standalone-header\">\r\n");
      out.write("            <h1><i class=\"bi bi-truck\" style=\"color:#3b6ef8;\"></i> Nuevo Rodado</h1>\r\n");
      out.write("            <p>Completá los datos del vehículo a registrar en el sistema.</p>\r\n");
      out.write("        </div>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ════════════════════════════════════════════════════\r\n");
      out.write("     FORMULARIO\r\n");
      out.write("     ════════════════════════════════════════════════════ -->\r\n");
      out.write("<div class=\"rodado-form-card\">\r\n");
      out.write("\r\n");
      out.write("    <form id=\"formRodado\"\r\n");
      out.write("          action=\"");
      out.print( request.getContextPath() );
      out.write("/RodadoServlet\"\r\n");
      out.write("          method=\"post\">\r\n");
      out.write("        <input type=\"hidden\" name=\"accion\" value=\"guardar\">\r\n");
      out.write("\r\n");
      out.write("        <!-- ── Sección 1: Clasificación ───────────────── -->\r\n");
      out.write("        <div class=\"card-section-header\">\r\n");
      out.write("            <i class=\"bi bi-tags-fill\"></i> Clasificación del vehículo\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-body-inner\">\r\n");
      out.write("            <div class=\"row g-3\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Tipo de Caja -->\r\n");
      out.write("                <div class=\"col-12 col-md-6\">\r\n");
      out.write("                    <div class=\"field-group\">\r\n");
      out.write("                        <label class=\"form-label-custom\" for=\"tipocaja\">Tipo de Caja</label>\r\n");
      out.write("                        <div class=\"select-wrap\">\r\n");
      out.write("                            <select class=\"form-select-custom\" id=\"tipocaja\" name=\"tipocaja\" required>\r\n");
      out.write("                                <option value=\"\" disabled selected>Seleccioná...</option>\r\n");
      out.write("                                <option value=\"MANUAL\">Manual</option>\r\n");
      out.write("                                <option value=\"AUTOMATICA\">Automática</option>\r\n");
      out.write("                                <option value=\"CVT\">CVT</option>\r\n");
      out.write("                                <option value=\"SECUENCIAL\">Secuencial</option>\r\n");
      out.write("                                <option value=\"DOBLE_EMBRAGUE\">Doble Embrague (DSG)</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Tipo de Vehículo -->\r\n");
      out.write("                <div class=\"col-12 col-md-6\">\r\n");
      out.write("                    <div class=\"field-group\">\r\n");
      out.write("                        <label class=\"form-label-custom\" for=\"tipo\">Tipo de Vehículo</label>\r\n");
      out.write("                        <div class=\"select-wrap\">\r\n");
      out.write("                            <select class=\"form-select-custom\" id=\"tipo\" name=\"tipo\" required>\r\n");
      out.write("                                <option value=\"\" disabled selected>Seleccioná...</option>\r\n");
      out.write("                                <option value=\"AUTO\">Auto</option>\r\n");
      out.write("                                <option value=\"CAMIONETA\">Camioneta</option>\r\n");
      out.write("                                <option value=\"MOTO\">Moto</option>\r\n");
      out.write("                                <option value=\"FURGON\">Furgón</option>\r\n");
      out.write("                                <option value=\"UTILITARIO\">Utilitario</option>\r\n");
      out.write("                                <option value=\"SUV\">SUV</option>\r\n");
      out.write("                                <option value=\"PICKUP\">Pick-up</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Tipo de Consumo -->\r\n");
      out.write("                <div class=\"col-12 col-md-6\">\r\n");
      out.write("                    <div class=\"field-group\">\r\n");
      out.write("                        <label class=\"form-label-custom\" for=\"tipoconsumo\">Tipo de Consumo</label>\r\n");
      out.write("                        <div class=\"select-wrap\">\r\n");
      out.write("                            <select class=\"form-select-custom\" id=\"tipoconsumo\" name=\"tipoconsumo\" required>\r\n");
      out.write("                                <option value=\"\" disabled selected>Seleccioná...</option>\r\n");
      out.write("                                <option value=\"NAFTA\">Nafta</option>\r\n");
      out.write("                                <option value=\"DIESEL\">Diesel</option>\r\n");
      out.write("                                <option value=\"GNC\">GNC</option>\r\n");
      out.write("                                <option value=\"ELECTRICO\">Eléctrico</option>\r\n");
      out.write("                                <option value=\"HIBRIDO\">Híbrido</option>\r\n");
      out.write("                                <option value=\"NAFTA_GNC\">Nafta / GNC</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Puertas -->\r\n");
      out.write("                <div class=\"col-12 col-md-6\">\r\n");
      out.write("                    <div class=\"field-group\">\r\n");
      out.write("                        <label class=\"form-label-custom\" for=\"puertas\">Cantidad de Puertas</label>\r\n");
      out.write("                        <div class=\"select-wrap\">\r\n");
      out.write("                            <select class=\"form-select-custom\" id=\"puertas\" name=\"puertas\" required>\r\n");
      out.write("                                <option value=\"\" disabled selected>Seleccioná...</option>\r\n");
      out.write("                                <option value=\"2\">2 puertas</option>\r\n");
      out.write("                                <option value=\"3\">3 puertas</option>\r\n");
      out.write("                                <option value=\"4\">4 puertas</option>\r\n");
      out.write("                                <option value=\"5\">5 puertas</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Tipo de Rodado -->\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"field-group\">\r\n");
      out.write("                        <label class=\"form-label-custom\" for=\"tipoderodado\">Tipo de Rodado</label>\r\n");
      out.write("                        <div class=\"select-wrap\">\r\n");
      out.write("                            <select class=\"form-select-custom\" id=\"tipoderodado\" name=\"tipoderodado\" required>\r\n");
      out.write("                                <option value=\"\" disabled selected>Seleccioná...</option>\r\n");
      out.write("                                <option value=\"SEDAN\">Sedán</option>\r\n");
      out.write("                                <option value=\"HATCHBACK\">Hatchback</option>\r\n");
      out.write("                                <option value=\"COUPE\">Coupé</option>\r\n");
      out.write("                                <option value=\"CABRIO\">Cabriolet / Convertible</option>\r\n");
      out.write("                                <option value=\"MONOVOLUMEN\">Monovolumen</option>\r\n");
      out.write("                                <option value=\"SUV\">SUV / Crossover</option>\r\n");
      out.write("                                <option value=\"PICKUP\">Pick-up</option>\r\n");
      out.write("                                <option value=\"FURGON\">Furgón</option>\r\n");
      out.write("                                <option value=\"MOTO_STANDARD\">Moto Standard</option>\r\n");
      out.write("                                <option value=\"MOTO_DEPORTIVA\">Moto Deportiva</option>\r\n");
      out.write("                                <option value=\"MOTO_CRUISER\">Moto Cruiser</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div><!-- /card-body-inner -->\r\n");
      out.write("\r\n");
      out.write("        <!-- ── Sección 2: Datos técnicos ─────────────── -->\r\n");
      out.write("        <div class=\"card-section-header\">\r\n");
      out.write("            <i class=\"bi bi-gear-fill\"></i> Datos técnicos\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-body-inner\">\r\n");
      out.write("            <div class=\"row g-3\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Patente -->\r\n");
      out.write("                <div class=\"col-12 col-md-6\">\r\n");
      out.write("                    <div class=\"field-group\">\r\n");
      out.write("                        <label class=\"form-label-custom\" for=\"patente\">Patente</label>\r\n");
      out.write("                        <div class=\"input-icon-wrap\">\r\n");
      out.write("                            <i class=\"bi bi-card-text\"></i>\r\n");
      out.write("                            <input type=\"text\"\r\n");
      out.write("                                   class=\"form-control-custom\"\r\n");
      out.write("                                   id=\"patente\"\r\n");
      out.write("                                   name=\"patente\"\r\n");
      out.write("                                   placeholder=\"Ej: AB 123 CD\"\r\n");
      out.write("                                   maxlength=\"10\"\r\n");
      out.write("                                   style=\"text-transform:uppercase;\"\r\n");
      out.write("                                   required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Motor Rodaje -->\r\n");
      out.write("                <div class=\"col-12 col-md-6\">\r\n");
      out.write("                    <div class=\"field-group\">\r\n");
      out.write("                        <label class=\"form-label-custom\" for=\"motorrodaje\">Motor / Rodaje (km)</label>\r\n");
      out.write("                        <div class=\"input-icon-wrap\">\r\n");
      out.write("                            <i class=\"bi bi-speedometer2\"></i>\r\n");
      out.write("                            <input type=\"number\"\r\n");
      out.write("                                   class=\"form-control-custom\"\r\n");
      out.write("                                   id=\"motorrodaje\"\r\n");
      out.write("                                   name=\"motorrodaje\"\r\n");
      out.write("                                   placeholder=\"Ej: 45000\"\r\n");
      out.write("                                   min=\"0\"\r\n");
      out.write("                                   required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Motor (cilindrada) -->\r\n");
      out.write("                <div class=\"col-12 col-md-6\">\r\n");
      out.write("                    <div class=\"field-group\">\r\n");
      out.write("                        <label class=\"form-label-custom\" for=\"motor\">Motor (cilindrada)</label>\r\n");
      out.write("                        <div class=\"input-icon-wrap\">\r\n");
      out.write("                            <i class=\"bi bi-cpu\"></i>\r\n");
      out.write("                            <input type=\"text\"\r\n");
      out.write("                                   class=\"form-control-custom\"\r\n");
      out.write("                                   id=\"motor\"\r\n");
      out.write("                                   name=\"motor\"\r\n");
      out.write("                                   placeholder=\"Ej: 1.6 TDI, 2.0 TSI\"\r\n");
      out.write("                                   required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Color -->\r\n");
      out.write("                <div class=\"col-12 col-md-6\">\r\n");
      out.write("                    <div class=\"field-group\">\r\n");
      out.write("                        <label class=\"form-label-custom\" for=\"color\">Color</label>\r\n");
      out.write("                        <div class=\"input-icon-wrap\">\r\n");
      out.write("                            <i class=\"bi bi-palette-fill\"></i>\r\n");
      out.write("                            <input type=\"text\"\r\n");
      out.write("                                   class=\"form-control-custom\"\r\n");
      out.write("                                   id=\"color\"\r\n");
      out.write("                                   name=\"color\"\r\n");
      out.write("                                   placeholder=\"Ej: Blanco, Negro, Gris Plata\"\r\n");
      out.write("                                   required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Baúl -->\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"field-group\">\r\n");
      out.write("                        <label class=\"form-label-custom\" for=\"baul\">Capacidad de Baúl (litros)</label>\r\n");
      out.write("                        <div class=\"input-icon-wrap\">\r\n");
      out.write("                            <i class=\"bi bi-briefcase-fill\"></i>\r\n");
      out.write("                            <input type=\"number\"\r\n");
      out.write("                                   class=\"form-control-custom\"\r\n");
      out.write("                                   id=\"baul\"\r\n");
      out.write("                                   name=\"baul\"\r\n");
      out.write("                                   placeholder=\"Ej: 390\"\r\n");
      out.write("                                   min=\"0\"\r\n");
      out.write("                                   required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div><!-- /card-body-inner -->\r\n");
      out.write("\r\n");
      out.write("        <!-- ── Footer / Botón ─────────────────────────── -->\r\n");
      out.write("        <div class=\"card-body-inner\" style=\"padding-top:0;\">\r\n");
      out.write("            <hr class=\"form-divider\">\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/rodado/agregarRodado.js\" class=\"back-link\">\r\n");
      out.write("<button type=\"submit\"\r\n");
      out.write("                    class=\"btn-guardar btn btn-success w-100\"\r\n");
      out.write("                    id=\"btn-confirmar\">\r\n");
      out.write("                <i class=\"bi bi-floppy2-fill\"></i>\r\n");
      out.write("                Guardar Rodado\r\n");
      out.write("            </button>\r\n");
      out.write("        </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("</div><!-- /rodado-form-card -->\r\n");
      out.write("\r\n");
 if (isStandalone) { 
      out.write("\r\n");
      out.write("    </div><!-- /form-standalone-inner -->\r\n");
      out.write("</div><!-- /form-standalone-wrap -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/agregarRodado.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
 } 
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
